# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4800bc434f00a32187f6a76b1d15968296aa4fdd73a38efdbde90a32b65116611f97d7c311849b8ce2f42f829ca06cb29dc75e5c7a8306a5907081923eeca1d0

test:
  secret_key_base: b2408a7ea5a94b4ed93dcaaecac62647319cbd8073ca178040e6c089b886ac4d2c38a74e28aceebc6e2ad77da46be7be27df0091029d542cb6e0d4109c722b29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
